APP-3873 WIP
SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles pull request #89
Opened 2021-05-20 14:05 UTC by symphony-annaLlorens

2021-05-21 08:06 UTC, symphony-jean-michael approved these changes

2021-05-21 09:11 UTC, symphony-adnane commented on docs/getting-started.md
> +## Unit Lengths
Sizing units

2021-05-21 09:12 UTC, symphony-adnane commented on src/components/atoms/_button.scss
> +  font-size: toRem($fontSize);
we can put it without a var

2021-05-21 09:14 UTC, symphony-adnane commented on src/components/atoms/_label.scss
> +  font-size: toRem($fontSize);
without var maybe

2021-05-21 09:14 UTC, symphony-adnane commented on src/components/atoms/_link.scss
> +  font-size: toRem($fontSize);
same

2021-05-21 09:15 UTC, symphony-adnane commented on src/components/atoms/_tooltip.scss
> +  font-size: toRem($fontSize);
same

2021-05-21 09:16 UTC, AliciaSymphony commented on src/components/atoms/_validation.scss
> -    margin: toEm(4, $fontSize) 0 0 0;
maybe the `0 0 0` were on purpose, I suggest not to change it in case it breaks something

2021-05-21 09:17 UTC, symphony-adnane commented on src/utils/_typography.scss
>    margin-block-start: auto;
can we make the margin utils apply with !important
there was a bug raised regarding this part :)
https://perzoinc.atlassian.net/browse/APP-4150

2021-05-21 09:20 UTC, AliciaSymphony commented on docs/getting-started.md
> + $UITOOLKIT_REM_BASE: 14;
it's 16, isn't it?

2021-05-21 09:44 UTC, AliciaSymphony requested changes
There is a big change on the Date Picker

Before:
<img src="https://user-images.githubusercontent.com/56824367/119117667-bfd89600-ba29-11eb-863d-065cc2284e67.png" />

After:
<img src"https://user-images.githubusercontent.com/56824367/119117700-c8c96780-ba29-11eb-9618-8831c45dd586.png" width="300px"/>

Could you have a second look please (and on the other affected)?


EDIT: It looks like the Date Picker's style was broken on storybook but it solved by the migration
<img src"https://user-images.githubusercontent.com/56824367/119118226-4c835400-ba2a-11eb-84fe-d1e192dc4905.png" />

2021-05-21 09:46 UTC, AliciaSymphony approved these changes

2021-05-21 09:51 UTC, AliciaSymphony requested changes
just some comments regarding the `margin` of the validation

2021-05-21 13:30 UTC, symphony-annaLlorens commented on docs/getting-started.md
> + $UITOOLKIT_REM_BASE: 14;
yes, this is if you want to modify it

2021-05-21 16:10 UTC, symphony-adnane commented
Please also modify storybook to not use 14px anymore
https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/blob/master/stories/stories.scss#L6

2021-05-24 07:14 UTC, symphony-annaLlorens commented on src/utils/_typography.scss
>    margin-block-start: auto;
We could handle it on the ticket and test different cases.

2021-05-24 08:18 UTC, AliciaSymphony commented on src/components/atoms/_label.scss
> +  font-size: 12;
I think that the unit is missing

2021-05-24 08:29 UTC, symphony-annaLlorens commented on src/components/atoms/_label.scss
> +  font-size: 12;
oh thanks :)

2021-05-24 08:31 UTC, AliciaSymphony approved these changes

2021-05-24 08:31 UTC, merged